### ISSUE TITLE
哈工大公函写作 信函结构修改意见 WJY

### ISSUE THREAD

**Issue by Milokita** [CQUPT-SMCA/Docs-Writing_Training#1]
修改意见如下：

- 注意信件抬头，格式及标点符号（格式自查）

- 开头应该先表明身份如姓名，所属学校以及写信目的（造访目的为参观）

- 简要直白地表达所希望达参观的部门或者参观内容 

- 预计到访的人数，时间及人员构成等相关信息（此处建议各信息单独一行）

- 表达感谢和被允许参观的期望

- 文件格式就直接使用txt格式就可以了，注意换行

信函整体应该简洁明了，不必使用过多的赞美之词。

**Comment by Milokita** [comment]
@Wangjunyi1999 已经改好了，问题很多

**Comment by Wangjunyi1999** [comment]
@Milokita 学长，按照要求已经改好了

**Comment by Milokita** [comment]
@Wangjunyi1999 新的版本整体有了较大的提升，干得漂亮

**Comment by Milokita** [comment]
@Wangjunyi1999 我后面做了一些注释，你可以看看还有没有要改的了

**Comment by Milokita** [comment]
这个issue是用来哈工大的，由于哈工大的已经结束特此将其关闭
