### ISSUE TITLE
哈工大公函写作 信函结构修改意见 HYZ

### ISSUE THREAD

**Issue by Milokita** [CQUPT-SMCA/Docs-Writing_Training#2]
修改意见如下：

- [x] 信件开头名称补充完整并注意标点符号

- [x] 首先应表明身份，写信目的以及如何获取的联系方式

- [x] 正式书信中应该避免文中出现“guys”之类的口语化词语

- [x] 建议移除"Here is the further information"等没有实际意义的语句以及"especially"等程度副词

- [x] 其余结构内容可以参考WJY的修改意见

- 署名部分也可以向左对齐

**Comment by heyuzhu** [comment]
历经了一系列事件，终于上传成功了，已按照要求修改。 @Milokita

**Comment by Milokita** [comment]
好的 @heyuzhu

**Comment by heyuzhu** [comment]
@Milokita

**Comment by heyuzhu** [comment]
修改好了

**Comment by Milokita** [comment]
新版本的具体问题已经提交了，请注意修改 @heyuzhu

**Comment by heyuzhu** [comment]
翻译已经上传，在原来哈工大公函文件里面，但是最下面那两个根目录下的file不知道怎么删除。 @Milokita

**Comment by Milokita** [comment]
@heyuzhu 没有找到你上传的文件在哪里，如果是后面的翻译作业请开创建一个新的文件夹

**Comment by Milokita** [comment]
另外，这个issue是用来哈工大的，由于哈工大的已经结束特此将其关闭
